import Head from "next/head";
import Navbar from "@/components/navbar/Navbar";
import { getEvents } from "@/services/supaService";
import { useEffect, useState } from "react";
import supabase from "../supabase/supabase";
import Event from "@/components/event/Event";

export default function events() {
  const [eventsList, setEventsList] = useState();
  const [error, setError] = useState();

  useEffect(() => {
    (async function getData() {
      let { data: eventsData, error } = await supabase
        .from("events")
        .select("*");
      if (error) {
        setError(error);
        return;
      }
      setEventsList(eventsData);
    })();
  }, []);

  console.log(eventsList);

  return (
    <>
      <Head>
        <title>events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        {eventsList &&
          eventsList.map((event) => {
            return <div key={event.name}>{event.name}</div>;
          })}
        <Event />
      </main>
    </>
  );
}
